### PR TITLE
fix file mode for build.fsx

### PR DESCRIPTION
**Pull request by Heather**

### CODE REVIEW

**Comment by gmpl** [comment]
Looks like it's still failing but this time I can't see any descriptive error message.

**Comment by Heather** [comment]
It's here :) `Could not find file "/Users/travis/build/gmpl/FsControl/makefile.fsx"` you forgot to add makefile.fsx actually, at least in F#+ build.fsx was calling it and then makefile.fsx is actually building project

**Comment by gmpl** [comment]
Oh, I missed that message, and the file as well.
I will add it and keep trying.

Thanks

**Comment by Heather** [comment]
@gmpl no problem :)

**Comment by gmpl** [comment]
Now it seems to build fine. The only remaining issue is the unit test project.
The problems seems to be that it doesn't download the nuget for MSBuild.Extension.Pack because the config that reference it is at a folder .nuget at the solution level.
I think I can fix it simply by removing that directory and adding the MSBuild.Extension.Pack in the .nuget of the test project, now the question is should I?
I think that structure was created by a template I used to create the test project and for instance myget understands it and is able to run the tests.
What do you think? Should I fix the project? Or is it better to adapt the build script (I don't know how) to look at the packages in that directory.

**Comment by Heather** [comment]
@gmpl I can take a look... after ~17 hours/tomorrow

**Comment by gmpl** [comment]
No worries. It's just a small detail, anyway I'm happy it compiles fine.
If you tell me that it's not a good practice to use that folder there I will move it.
Thanks in advance.

**Pull request merged**
